spring:
    datasource:
        url: jdbc:mysql://localhost:3306/nology_library?allowPublicKeyRetrieval=true&&useSSL=false&serverTimezone=UTC
        username: root


auth0:
    audience: localhost:8080
    spring:
        security:
            oauth2:
                resourceserver:
                    jwt:
                        issuer_uri: https://dev-634ppvbs.eu.auth0.com/
